package com.ecom.product_command_service.Entity;

public enum OperationType {
//    ADD_PRODUCTS,
//    DELETE_PRODUCTS
    ADD_PRODUCTS,
    UPDATE_PRODUCTS,
    DELETE_PRODUCTS,

    ADD_CATEGORY_PRODUCTS,
    UPDATE_CATEGORY_PRODUCTS,
    DELETE_CATEGORY_PRODUCTS,

    ADD_LIST_CATEGORY_PRODUCTS,
    UPDATE_LIST_CATEGORY_PRODUCTS,
    DELETE_LIST_CATEGORY_PRODUCTS,

    ADD_PRODUCTS_VARIENT,
    UPDATE_PRODUCTS_VARIENT,
    DELETE_PRODUCTS_VARIENT,

    ADD_LIST_PRODUCTS_VARIENT,
    UPDATE_LIST_PRODUCTS_VARIENT,
    DELETE_LIST_PRODUCTS_VARIENT
}
